In [2]:
import numpy as np
import pandas as pd
from template_lr import LinearRegressionGD

In [3]:
model2=LinearRegressionGD(
    feature_cols=[
        'area_sqm',
        'area_sqm^2'
    ],
    target_col='price_k',
    
)
model2.fit("house_data2.csv")
model2.coef_table()

      feature    w_scaled  w_original
0   intercept  383.035678  -31.306693
1    area_sqm  125.078558    3.863644
2  area_sqm^2   -3.386468   -0.000468

In [4]:
model3=LinearRegressionGD(
    feature_cols=[
        'area_sqm',
        'area_sqm^2',
        'area_sqm^3'
    ],
    target_col='price_k',
    
)
model3.fit("house_data2.csv")
model3.coef_table()

      feature    w_scaled  w_original
0   intercept  383.035678  -24.686181
1    area_sqm  110.801600    3.422632
2  area_sqm^2   40.686826    0.005618
3  area_sqm^3  -30.772433   -0.000023

In [5]:
model4=LinearRegressionGD(
    feature_cols=[
        'area_sqm',
        'area_sqm^2',
        'area_sqm^3',
        'area_sqm^4'
    ],
    target_col='price_k',
    
)
model4.fit("house_data2.csv")
model4.coef_table()

      feature    w_scaled    w_original
0   intercept  383.035678 -3.907738e+00
1    area_sqm   95.406092  2.947069e+00
2  area_sqm^2   48.623340  6.714258e-03
3  area_sqm^3    5.424338  4.003226e-06
4  area_sqm^4  -30.011809 -1.224380e-07