In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
print(df.size)
print(df.shape)
print(df.ndim)

10692
(891, 12)
2

In [69]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Fare_zscore'],
      dtype='object')

In [10]:
print(df.index)

RangeIndex(start=0, stop=891, step=1)

In [11]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [12]:
df.values#转化成二维数组

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [13]:
df.memory_usage()#每一列占多少字节

Index           132
PassengerId    7128
Survived       7128
Pclass         7128
Name           7128
Sex            7128
Age            7128
SibSp          7128
Parch          7128
Ticket         7128
Fare           7128
Cabin          7128
Embarked       7128
dtype: int64

In [18]:
print(df.iat[0,8])
print(df.at[0,'Age'])

A/5 21171
22.0

In [20]:
df.info#注意这个是错误的
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [36]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [72]:
print(df.nunique())#每一列有多少不同的值

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             91
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
Fare_zscore    255
dtype: int64

In [74]:
print(df.isnull())#所有value返回真值

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False  False  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked  Fare_zscore
0    False   True     False        False
1    False  False     False        False
2    False   True     False        False
3    False  False     False        False
4    False   True     False        False
..     ...    ...       ...          ...
886  False   True     False        False
887  False  False     False        False
888  False   True     False        False
889  False  False     False        False
890  False   True     False        False

[891 rows x 13 columns]

In [75]:
print(df.head())
print("\n\n\n")
print(df.tail(3))
print("\n\n\n")
print(df.sample(5))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked  Fare_zscore
0      0         A/5 21171   7.2500   NaN        S    -0.545549
1      0          PC 17599  71.2833   C85        C    -0.164217
2      0  STON/O2. 3101282   7.9250   NaN        S    -0.488239
3      0            113803  53.1000  C123        S    -0.396205
4      0            373450   8.0500   NaN        S    -0.477626




     PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex       Age  SibSp  Parch      Ticket   Fare Cabin Embarked  \
888  female  25.14062      1      2  W./C. 6607  23.45   NaN        S
889    male  26.00000      0      0      111369  30.00  C148        C
890    male  32.00000      0      0      370376   7.75   NaN        Q

     Fare_zscore
888     0.829880
889    -0.690922
890    -0.503097




     PassengerId  Survived  Pclass  \
426          427         1       2
252          253         0       1
234          235         0       2
466          467         0       2
744          745         1       3

                                            Name     Sex       Age  SibSp  \
426  Clarke, Mrs. Charles V (Ada Maria Winfield)  female  28.00000      1
252                    Stead, Mr. William Thomas    male  62.00000      0
234            Leyson, Mr. Robert William Norman    male  24.00000      0
466                        Campbell, Mr. William    male  29.87763      0
744                           Stranden, Mr. Juho    male  31.00000      0

     Parch             Ticket    Fare Cabin Embarked  Fare_zscore
426      0               2003  26.000   NaN        S     0.397828
252      0             113514  26.550   C87        S    -0.734938
234      0         C.A. 29566  10.500   NaN        S    -0.757388
466      0             239853   0.000   NaN        S    -1.539954
744      0  STON/O 2. 3101288   7.925   NaN        S    -0.488239

In [78]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Fare_zscore      0
dtype: int64

In [33]:
#排序
df.sort_values('Fare',ascending=False).head(3)#递减

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C

In [35]:
df.sort_values(['Pclass','Age']).head(4)
#排序优先级，第一个优先，值相同第二个
## True代表升序，False代表降序
#df.sort_values(by=['部门', '绩效'], ascending=[True, False])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S

In [37]:
df.groupby('Pclass')['Survived'].mean()#各个船舱的生还率

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [38]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [48]:
df.groupby(['Sex','Pclass']).groups

{('female', 1): [1, 3, 11, 31, 52, 61, 88, 136, 151, 166, 177, 194, 195, 215, 218, 230, 256, 257, 258, 268, 269, 275, 290, 291, 297, 299, 306, 307, 309, 310, 311, 318, 319, 325, 329, 334, 337, 341, 356, 366, 369, 375, 380, 383, 393, 412, 435, 457, 486, 496, 498, 504, 513, 520, 523, 537, 539, 540, 556, 558, 571, 577, 581, 585, 591, 609, 627, 641, 669, 689, 700, 708, 710, 716, 730, 742, 759, 763, 765, 779, 781, 796, 809, 820, 829, 835, 842, 849, 853, 856, 862, 871, 879, 887], ('female', 2): [9, 15, 41, 43, 53, 56, 58, 66, 84, 98, 123, 133, 161, 190, 199, 211, 237, 247, 259, 272, 303, 312, 316, 322, 323, 327, 345, 346, 357, 387, 389, 399, 416, 417, 426, 427, 432, 437, 440, 443, 446, 458, 472, 473, 506, 516, 518, 526, 530, 535, 546, 576, 580, 596, 600, 608, 615, 618, 635, 651, 670, 706, 717, 720, 726, 747, 750, 754, 772, 774, 801, 854, 865, 866, 874, 880], ('female', 3): [2, 8, 10, 14, 18, 19, 22, 24, 25, 28, 32, 38, 39, 40, 44, 47, 49, 68, 71, 79, 82, 85, 100, 106, 109, 111, 113, 114, 119, 128, 132, 140, 141, 142, 147, 156, 167, 172, 180, 184, 186, 192, 198, 205, 208, 216, 229, 233, 235, 240, 241, 246, 251, 254, 255, 264, 274, 276, 279, 289, 293, 300, 315, 328, 330, 347, 358, 359, 362, 367, 368, 374, 376, 381, 394, 396, 402, 404, 409, 415, 419, 423, 431, 436, 448, 469, 474, 479, 483, 485, 501, 502, 503, 533, 534, 541, 542, 554, 559, 564, ...], ('male', 1): [6, 23, 27, 30, 34, 35, 54, 55, 62, 64, 83, 92, 96, 97, 102, 110, 118, 124, 137, 139, 155, 168, 170, 174, 185, 187, 209, 224, 245, 248, 252, 262, 263, 270, 273, 284, 295, 298, 305, 331, 332, 336, 339, 351, 370, 373, 377, 390, 430, 434, 438, 445, 447, 449, 452, 453, 456, 460, 462, 467, 475, 484, 487, 492, 493, 505, 507, 512, 515, 527, 536, 544, 545, 550, 555, 557, 572, 583, 587, 599, 602, 604, 607, 621, 625, 630, 632, 633, 645, 647, 659, 660, 662, 671, 679, 681, 690, 694, 698, 701, ...], ('male', 2): [17, 20, 21, 33, 70, 72, 78, 99, 117, 120, 122, 134, 135, 144, 145, 148, 149, 150, 178, 181, 183, 191, 193, 213, 217, 219, 221, 226, 228, 232, 234, 236, 238, 239, 242, 249, 265, 277, 288, 292, 308, 314, 317, 340, 342, 343, 344, 361, 385, 397, 398, 405, 407, 413, 418, 439, 450, 463, 466, 476, 481, 529, 543, 547, 549, 551, 562, 570, 582, 586, 594, 619, 626, 637, 655, 658, 665, 666, 672, 673, 674, 684, 685, 695, 705, 714, 722, 723, 728, 732, 733, 734, 755, 757, 791, 795, 800, 808, 812, 817, ...], ('male', 3): [0, 4, 5, 7, 12, 13, 16, 26, 29, 36, 37, 42, 45, 46, 48, 50, 51, 57, 59, 60, 63, 65, 67, 69, 73, 74, 75, 76, 77, 80, 81, 86, 87, 89, 90, 91, 93, 94, 95, 101, 103, 104, 105, 107, 108, 112, 115, 116, 121, 125, 126, 127, 129, 130, 131, 138, 143, 146, 152, 153, 154, 157, 158, 159, 160, 162, 163, 164, 165, 169, 171, 173, 175, 176, 179, 182, 188, 189, 196, 197, 200, 201, 202, 203, 204, 206, 207, 210, 212, 214, 220, 222, 223, 225, 227, 231, 243, 244, 250, 253, ...]}

In [49]:
df.groupby(['Sex', 'Pclass'])['Survived'].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [50]:
df.groupby('Pclass')['Age'].agg(['mean','min','max','count'])

             mean   min   max  count
Pclass
1       38.233441  0.92  80.0    186
2       29.877630  0.67  70.0    173
3       25.140620  0.42  74.0    355

In [52]:
df.groupby(['Sex','Pclass']).agg(
    {
        'Survived':'mean',
        'Age':['mean','min','max'],
        'Fare':'mean',
        'PassengerId':'count'
    }
    
)

               Survived        Age                    Fare PassengerId
                   mean       mean   min   max        mean       count
Sex    Pclass
female 1       0.968085  34.611765  2.00  63.0  106.125798          94
       2       0.921053  28.722973  2.00  57.0   21.970121          76
       3       0.500000  21.750000  0.75  63.0   16.118810         144
male   1       0.368852  41.281386  0.92  80.0   67.226127         122
       2       0.157407  30.740707  0.67  70.0   19.741782         108
       3       0.135447  26.507589  0.42  74.0   12.661633         347

In [53]:
df.groupby('Sex').agg(
    生还率   = ('Survived', 'mean'),
    平均年龄  = ('Age', 'mean'),
    最高票价  = ('Fare', 'max'),
    人数     = ('PassengerId', 'count')
)

             生还率       平均年龄      最高票价   人数
Sex
female  0.742038  27.915709  512.3292  314
male    0.188908  30.726645  512.3292  577

In [57]:
df['Age']=df['Age'].fillna(
    df.groupby('Pclass')['Age'].transform('mean')
)

In [63]:
df['Fare_zscore'] = df.groupby('Pclass')['Fare'].transform(
    lambda x: (x - x.mean()) / x.std()
)
df['Fare_zscore']

0     -0.545549
1     -0.164217
2     -0.488239
3     -0.396205
4     -0.477626
         ...
886   -0.571063
887   -0.690922
888    0.829880
889   -0.690922
890   -0.503097
Name: Fare_zscore, Length: 891, dtype: float64

In [64]:
df.groupby('Embarked').filter(lambda x: len(x) > 100)#返回原始行

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_zscore
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00000,1,0,A/5 21171,7.2500,NaN,S,-0.545549
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00000,1,0,PC 17599,71.2833,C85,C,-0.164217
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00000,0,0,STON/O2. 3101282,7.9250,NaN,S,-0.488239
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00000,1,0,113803,53.1000,C123,S,-0.396205
4,5,0,3,"Allen, Mr. William Henry",male,35.00000,0,0,373450,8.0500,NaN,S,-0.477626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.00000,0,0,SOTON/OQ 392076,7.0500,NaN,S,-0.562529
886,887,0,2,"Montvila, Rev. Juozas",male,27.00000,0,0,211536,13.0000,NaN,S,-0.571063
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00000,0,0,112053,30.0000,B42,S,-0.690922
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,25.14062,1,2,W./C. 6607,23.4500,NaN,S,0.829880
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00000,0,0,111369,30.0000,C148,C,-0.690922

In [65]:
df.groupby('Pclass').filter(
    lambda x: x['Survived'].mean() > 0.4
)#剔除整个第三仓

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_zscore
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,-0.164217
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,-0.396205
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,-0.411993
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,0.701225
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,-0.734938
...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,0.397828
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,-0.757388
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,-0.571063
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,-0.690922
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,-0.690922

In [67]:
df.groupby('Pclass').apply(
    lambda x: x.nlargest(3, 'Fare')
)[[ 'Name', 'Pclass', 'Fare']]

D:\Temp\ipykernel_54072\3451632663.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Pclass').apply(

                                          Name  Pclass      Fare
Pclass
1      258                    Ward, Miss. Anna       1  512.3292
       679  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
       737              Lesurer, Mr. Gustave J       1  512.3292
2      72                 Hood, Mr. Ambrose Jr       2   73.5000
       120         Hickman, Mr. Stanley George       2   73.5000
       385           Davies, Mr. Charles Henry       2   73.5000
3      159          Sage, Master. Thomas Henry       3   69.5500
       180        Sage, Miss. Constance Gladys       3   69.5500
       201                 Sage, Mr. Frederick       3   69.5500

In [68]:
def survival_summary(group):
    return pd.Series({
        '人数':    len(group),
        '生还人数': group['Survived'].sum(),
        '生还率':  group['Survived'].mean().round(3),
        '平均年龄': group['Age'].mean().round(1)
    })

df.groupby('Sex').apply(survival_summary)

D:\Temp\ipykernel_54072\121654566.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Sex').apply(survival_summary)

           人数   生还人数    生还率  平均年龄
Sex
female  314.0  233.0  0.742  27.9
male    577.0  109.0  0.189  30.1